name: studious_waffle
description: "Ad Creator, Poster Generator and TikTok-like Feed App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # የለቀቅናቸው/የተጠቀምናቸው ፓኬጆች
  flutter_colorpicker: ^1.1.0
  path_provider: ^2.1.2
  video_player: ^2.8.2
  ffmpeg_kit_flutter: ^6.0.3
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
